#!/usr/bin/env python3

import binascii
from trezorlib import ed25519raw

number=1
seckeys=[
b'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT1',
b'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT2',
b'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT3',
b'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTq1',
b'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTq2',
b'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTq3'
]

def hex_to_c(s):
    return '"\\x' + '\\x'.join([s[i:i + 2] for i in range(0, len(s), 2)]) + '"'

with open("keys.txt","wt") as keyfile:
    for seckey in seckeys:
        print('\nNo.', number)
        seckey_hex = binascii.hexlify(seckey).decode()
        keyfile.write("\nseckey :")       
        keyfile.write(seckey_hex)
        keyfile.write("\n(const uint8_t *)")
        keyfile.write(hex_to_c(seckey_hex))
        keyfile.write(",\n")
        print('seckey:', seckey_hex)
        print('(const uint8_t *)', hex_to_c(seckey_hex))
        pubkey = ed25519raw.publickey(seckey)
        pubkey_hex = binascii.hexlify(pubkey).decode()
        keyfile.write("\npubkey  : ")       
        keyfile.write(pubkey_hex)
        keyfile.write("\n(const uint8_t *)")
        keyfile.write(hex_to_c(pubkey_hex))
        keyfile.write(",\n")
        print('pubkey:', pubkey_hex)
        print('(const uint8_t *)', hex_to_c(pubkey_hex))        
        number=number+1
    keyfile.close()
